 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Zkh7YHKPIK0qESBiUt9VT7v7TTvvlDw',
    appId: '1:422530131010:web:19ea321b831890dafc39db',
    messagingSenderId: '422530131010',
    projectId: 'fitverse-b1603',
    authDomain: 'fitverse-b1603.firebaseapp.com',
    databaseURL: 'https://fitverse-b1603-default-rtdb.firebaseio.com',
    storageBucket: 'fitverse-b1603.firebasestorage.app',
    measurementId: 'G-CK28S1G2E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu_bkoW5J94IzO9K1rxsGrmSaOuPn9TKs',
    appId: '1:422530131010:android:6ec29075922d11fbfc39db',
    messagingSenderId: '422530131010',
    projectId: 'fitverse-b1603',
    databaseURL: 'https://fitverse-b1603-default-rtdb.firebaseio.com',
    storageBucket: 'fitverse-b1603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeIoERxC5mb3BIqRwEPjbnEBvL0lUop94',
    appId: '1:422530131010:ios:3b996123e50ad474fc39db',
    messagingSenderId: '422530131010',
    projectId: 'fitverse-b1603',
    databaseURL: 'https://fitverse-b1603-default-rtdb.firebaseio.com',
    storageBucket: 'fitverse-b1603.firebasestorage.app',
    androidClientId: '422530131010-uf19gq4fj1hs465n4mdb09l2r7tqiqbh.apps.googleusercontent.com',
    iosClientId: '422530131010-necgnkbvulkesmaqp77gc4kqheepdfgl.apps.googleusercontent.com',
    iosBundleId: 'com.webrtccaller',
  );
}
